doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            App\Api\User\Entity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Api/User/Entity'
                prefix: 'App\Api\User\Entity'
                alias: App\Api\User
            App\Security\Entity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Security/Entity'
                prefix: 'App\Security\Entity'
                alias: App\Security\TokenRequest
            App\Api\Car\Entity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Api/Car/Entity'
                prefix: 'App\Api\Car\Entity'
                alias: App\Api\Car
            App\Api\Garage\Entity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Api/Garage/Entity'
                prefix: 'App\Api\Garage\Entity'
                alias: App\Api\Garage
            App\Api\Club\Entity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Api/Club/Entity'
                prefix: 'App\Api\Club\Entity'
                alias: App\Api\Club
            App\Api\Post\Entity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Api/Post/Entity'
                prefix: 'App\Api\Post\Entity'
                alias: App\Api\Post
            App\Api\Category\Entity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Api/Category/Entity'
                prefix: 'App\Api\Category\Entity'
                alias: App\Api\Category
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system