nelmio_api_doc:
  documentation:
    servers:
      - url: 'http://carmeet.lndo.site'
        description: 'API'
    info:
      title: Carmeet API
      description: Carmeet API
      version: 1.0.0
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: []
  areas:
    default:
      path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
        - ^/api(?!/doc$)