kernel:
    resource: ../../src/Kernel.php
    type: annotation

controllers:
    resource: ../../src/Controller/
    type: annotation

controllers.api:
    resource: ../../src/Api/*/Controller/*
    type: annotation

api_login_check:
    path: /api/login_check